### ISSUE TITLE
Chat IO issues after react native component get unmount

### ISSUE THREAD

**Issue by URvesh109** [livechat/react-native-chatio#5]
onChatLoaded(ref) {
        this.chat = ref;
        ref.updateCustomer({
            name: this.props.user.user_nicename,
            email: this.props.user.user_email,
        })
            .then(() => {
                this.chatIo.openChat();
                this.setState({loading: false});
            })
            .catch((e) => {
                console.log(e);
                this.setState({loading: false});
            });
    }

 render() {
        const {user} = this.props;
        return (
            <View style={{flex: 1}}>
                {this.state.loading ? <Loading /> : null}
                <ChatIO
                    onLoaded={this.onChatLoaded}
                    onChatStarted={this.onChatStarted}
                    clientId={clientId}
                    redirectUri={redirectUri}
                    license={licenseId}
                    ref={(input) => (this.chatIo = input)}
                    bottomOffset={40}
                    greeting={`Hallo ${user.user_nicename}! Was können wir für dich tun?`}
                />
            </View>
        );
    }

Everthing is working fine at the first load, but after I am logout from app and re-login following issue persist, i.e

Once the chatio component get unmounted and after again mounting that component the onLoaded method does not get called. So the chat io screen is blank.

**Comment by sagark1510** [comment]
try this out



       componentWillUnmount() {
          GLOBAL.customerSDK.auth.invalidate();
          GLOBAL.customerSDK.disconnect();
          GLOBAL.customerSDK.destroy();
          GLOBAL.customerSDK = undefined;
       }
